created skeleton, mysql schema. Implemented all data for component an…
Arwen-Fec/carousel-module pull request #2
Opened 2020-04-30 19:10 UTC by Malyarc

…d seeding file. Server/DB/Client all connect and works

2020-04-30 19:32 UTC, ikheraj17 commented on database/schema.sql
> +INSERT INTO colors (id, product_id, color_name, color_url) VALUES (1, 1, "Black", "https://hrr45fec.s3-us-west-1.amazonaws.com/mask_colors/il_1588xN.2290355171_9ptb.jpg");
Very easy to read insertion of our 1st product pictures! lgtm!

2020-04-30 19:34 UTC, ikheraj17 commented on database/seed.js
> +
Maybe handle errors with the callback function here? Otherwise lgtm!

2020-04-30 19:39 UTC, diversifiedmechanic commented on database/seed.js
> +
Should the `colorURL`  be referencing a URL that is stored in your S3 bucket?

2020-04-30 20:41 UTC, mta630 requested changes
It mostly looks good but i'm curious about the urlencode as well as I think you should have error handling in your seeding file and a script to run the seed file

2020-04-30 20:41 UTC, mta630 commented on database/seed.js
> +
Ya I think you will need to change that faker.image.imageUrl() to grab pictures from an array of URLS from your s3, I think you were planning on doing that anyhow. Also I agree that you should have some sort of error handling for your query.

2020-04-30 20:41 UTC, mta630 commented on package.json
> +    "server-dev": "nodemon server/server.js"
You'll need to create a script here to run the seed file

2020-04-30 20:41 UTC, mta630 commented on server/server.js
> +
I am just curious what your reason behind using urlencoded is here?

2020-04-30 21:42 UTC, Malyarc commented on database/seed.js
> +
Hmm to clarify @Sam do we need our dummy data to have real imgs from S3 as well? 

So the page you are looking at is just populating the dummy data. I inserted the 10 real ones to display inside my Schema.sql file so I could source it. Sorry for not clarifying earlier

2020-04-30 23:20 UTC, Joseph765 commented
lgtm other than what micheal pointed out!

2020-04-30 23:38 UTC, mta630 approved these changes

2020-05-01 16:58 UTC, Joseph765 reviewed
Great job!

2020-05-01 16:58 UTC, Joseph765 commented on package.json
> +    "seed": "node database/seed.js"
Looks good and you added a seeding script!

2020-05-01 16:59 UTC, Joseph765 approved these changes
I approve!

2020-05-01 17:36 UTC, mta630 approved these changes
Looks great! approved

2020-05-01 18:03 UTC, merged